#################################
#####         语言          #####
#################################
lang:
  cn: "lang_cn.yml"

#################################
#####         配置          #####
#################################
#命令类型前缀
#(修改后需要重启服务器生效)
cmdFuncPrefix: "/f "

#重新读取配置文件的权限
per_cmd_admin: "cmd.admin"

#################################
#####       命令转换        #####
#################################
convert:
  #true: 命令无转换配置时禁止使用
  #false: 命令无转换配置时不处理
  defaultDeny: false
  #转换
  converts:
    land:                   #命令名(大小写不敏感)
      aliases:             #别名列表(可选,默认无)(别名与命令名具有相同地位)
        - "l"
      types:
        1:                      #数字必须从1开始递增(检测会按顺序从小到大进行,检测成功则不进行后面的检测)
          conArgs: 0          #条件,变量数量,>=0(不包括命令名)(可选,默认-1,-1表示无限制)
          cmd: "/f ld"         #命令转换(可选,默认不转换)(注1)
          per: ""                 #权限控制(可选,默认无权限)
        2:
          cmd: "/f ld s {1}"
    go:
      types:
        1:
          cmd: "/f ld go {1}"
    zisha:
      aliases:
        - "zisa"
        - "zhisa"
        - "zhisha"
      types:
        1:
          cmd: "/suicide"
    cmd:
      types:
        1:
          cmd: "/f mp"
          
#################################
#####          注           #####
#################################
###注1### 
#1. 命令转换允许变量:
#  {name}: 代表玩家名
#  {x}
#  {x,}
#  {,y}
#  {x,y}
#  {,}
#2. 命令转换允许转换成任意的聊天信息而并非以/开头的命令