#################################
#####         语言          #####
#################################
lang:
  cn: "lang_cn.yml"

#################################
#####         配置          #####
#################################
#命令类型前缀
#(修改后需要重启服务器生效)
funcPrefix: "/f "

#命令无配置时是否禁止使用(true表示禁止)
#此处禁止的命令指以'/'开头的游戏命令
defaultDeny: false
